language: c 

cache:
    apt: true

os:
    - linux
    - osx

env:
    - TEST_SUITE=short
    - TEST_SUITE=cx
    - TEST_SUITE=long
    - TEST_SUITE=relativistic
    - TEST_SUITE=geminal

osx_image: xcode7.3
# Could add more toolchains in future
# with something like:
#
# sources:
#   - ubuntu-toolchain-r-test
# packages:
#   - gfortran-6.1
#
# or similar
addons:
    apt:
        sources:
            - george-edison55-precise-backports
            - ubuntu-toolchain-r-test
        packages:
            - perl
            - cmake
            - cmake-data
            - gfortran
            - gcc-6
            - python3
            - gfortran-6
            - liblapack-dev

before_install:
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install gcc; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew upgrade python; fi
    - export FC=gfortran-6
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export FC=gfortran; fi

# We are only really interested in the short tests for now
script:
  - mkdir build && cd build
  - cmake --version
  - cmake ..
  - cmake --build . -- -j2
  - ctest -L $TEST_SUITE -j2

after_script:
  - cat Testing/Temporary/LastTest.log


matrix:
    fast_finish: true
    allow_failures:
        - env: TEST_SUITE=long
        - env: TEST_SUITE=relativistic
        - env: TEST_SUITE=geminal
        - os: osx

notifications:
  email: false
  slack: quantum-crystals:c4wMeP4do0xwgnNyHuGefmQH
