#!/bin/bash
#
# Usage
#
# In the Tonto job folder, type:
#
#    make-rgbi-dials [--do-tonto] 
#
# Output
#
#   rgbi-dial-diagrms.pdf
#
# Requirements
#
# - This script
# - The rgbi-dial-diagrms.tex file
# - tonto
# - The stdin file for a Tonto RGBI job <---
# - The rgbi-dial-figures.tex made by the Tonto RGBI job
# - tonto

# Defaults
do_tonto=0
do_H=1

# Process options
while [[ "$#" > 0 ]]; do case $1 in
  --do-tonto) do_tonto=1;;
  --do-H)     do_H=1;;
  --no-H)     do_H=0;;
  *) echo "Unknown parameter passed: $1"; exit 1;;
esac; shift; done

# tonto: get bondtable.tex
if [[ do_tonto -gt 0 ]]; then
   tonto
fi

# Get RGBI tex template
cp ~/bin/cf-pastebin.tex .
cp ~/bin/rgbi-dial-header.tex .
cp ~/bin/rgbi-dial-diagrams.tex .
cp ~/bin/mol2chemfig.sty .

if [[ do_H -gt 0 ]]; then

   # Make the pdf of dial table
   pdflatex rgbi-dial-table+H.tex >& /dev/null
   pdflatex rgbi-dial-table+H.tex >& /dev/null

   # Crop
   pdfcrop  rgbi-dial-table+H.pdf
   mv rgbi-dial-table+H-crop.pdf rgbi-dial-table+H.pdf

else

   # Make the pdf of dial table
   pdflatex rgbi-dial-table-H.tex >& /dev/null
   pdflatex rgbi-dial-table-H.tex >& /dev/null

   # Crop
   pdfcrop  rgbi-dial-table-H.pdf
   mv rgbi-dial-table-H-crop.pdf rgbi-dial-table-H.pdf

fi

