#!/bin/bash
#
# Usage
#
# In the Tonto job folder, type:
#
#    make-rgbi-dials [--do-tonto] 
#
# Output
#
#   rgbi-dial-diagrms.pdf
#
# Requirements
#
# - This script
# - tonto
# - A stdin file for a tonto RGBI job <---
# - The rgbi-dial-diagrams.tex file, made by tonto
# - The rgbi-dial-header.tex included here
# - pdflatex with full latex installation esp. TikZ
# - pdfcrop

# Defaults
do_tonto=0

# Process options
while [[ "$#" > 0 ]]; do case $1 in
  --do-tonto) do_tonto=1;;
  *) echo "Unknown parameter passed: $1"; exit 1;;
esac; shift; done

# tonto: get bondtable.tex
if [[ do_tonto -gt 0 ]]; then
   tonto
fi

# Dial diagram template
cp ~/bin/rgbi-dial-header.tex .
cp ~/bin/rgbi-dial-diagrams.tex .

# Make the pdf image
pdflatex rgbi-dial-diagrams.tex >& /dev/null
pdflatex rgbi-dial-diagrams.tex >& /dev/null

# Crop
pdfcrop  rgbi-dial-diagrams.pdf
mv rgbi-dial-diagrams-crop.pdf rgbi-dial-diagrams.pdf

