#!/bin/bash
rel="0.00001"
tmp1=$(mktemp)
tmp2=$(mktemp)
ignore="^\s*$|^\s*Timer started|^\s*Version:|^\s*Platform:|^\s*Build-date: \
|^\s*Wall-clock time taken|^\s*CPU time taken|^\s*time taken \
|^\s*Warning from|^\s*Routine call stack:|^\s*Call \s*Routine name \s*Memory Used \
|^\s*\d+\.\s*[A-Z.]+:\w+\s+\d+\s*$|Memory usage report \
|^\s*Memory currently used      =|^\s*Maximum memory used        = \
|^\s*Memory blocks used         =|^\s*Maximum memory blocks used = \
|^\s*Memory limit               =|^\s*Call stack level           = \
|^\s*Maximum call stack depth   =|^\s*Warning from MOLECULE.MAIN:run ... memory leak \
|^\s*SYSTEM: Memory usage report:"
egrep -v "$ignore" $1 > $tmp1
egrep -v "$ignore" $2 > $tmp2
numdiff -r $rel $tmp1 $tmp2 2>&1 > /dev/null
retval=$?
rm $tmp1 $tmp2
exit $retval
